# Config file for mesh.d

[client-config]
	remote-ip-file = "./configs/ip_file"
	local-accept   = "4440"
	cert           = "/a/b/x/cert.crt"
	key            = "/a/b/z/pem.key"
	
# this will be an array to support multiple entries (in future).
[reverse-proxy]
	http-path    = "/registry/"
	connect-ip   = "127.0.0.1"
	connect-port = "7777"
	enable       = "true"

#nothing here.
