# Config file for mesh.d

[client-config]
    remote-ip-file = "./configs/ip_file_2"
    local-hostname = "localhost"
    cert           = "./conf/cert.crt"
    key            = "./conf/pem.key"

#nothing here.
