[build-from]
        base="alpine"
        version="latest"

[build-compile]
	version="0.1"
	static="false"
	source="/nodes/ukamaOS/distro/system/deviced"
	cmd="make"
	bin_from="/nodes/ukamaOS/distro/system/deviced/device.d"
	bin_to="/sbin"

[capp-exec]
	name="deviced"
	version="latest"
	bin="device.d"
	path="/sbin"
        autostart="false"
        autorestart="true"
        startretries=5
	group="service"
