[build-from]
        base="alpine"
        version="latest"

[build-compile]
	version="0.1"
	static="false"
	source="/nodes/apps/gps"
	cmd="make"
	bin_from="/nodes/apps/gps/gps.d"
	bin_to="/sbin"

[capp-exec]
	name="gpsd"
	version="latest"
	bin="gps.d"
	path="/sbin"
	autostart="false"
    autorestart="true"
    startretries=5
	group="service"
