[build-from]
	base="alpine"
	version="latest"

[build-compile]
	version="0.1"
	static="false"
	source="/nodes/ukamaOS/distro/system/noded"
	cmd="make"
	bin_from="/nodes/ukamaOS/distro/system/noded/build/node.d"
	bin_to="/sbin/"

[capp-exec]
	name="noded"
	version="latest"
	autostart="false"
	autorestart="true"
	startretries=5
	bin="node.d"
	path="/sbin"
	args="--p /mfgdata/property/property.json --i /tmp/sys/inventory_db"
	group="on-boot"
