[build-from]
        base="alpine"
        version="latest"

[build-compile]
	version="0.1"
	static="false"
	source="/nodes/ukamaOS/distro/system/rlog"
	cmd="make"
	bin_from="/nodes/ukamaOS/distro/system/rlog/rlog.d"
	bin_to="/sbin"

[capp-exec]
	name="rlog"
	version="latest"
	bin="rlog.d"
	path="/sbin"
       	autostart="false"
        autorestart="true"
        startretries=5
        group="service"
