
#
# Sample config file to build capp for the Ukama's Virtual Node.
#

# Base image to use to build container. Examples are alpine, Ubuntu, etc.
[build-from]
	base="alpine"
	version="latest"

[build-compile]
	version="0.1"
	static="false"
	source="/home/kashif/work/ukama/ukamaOS/distro/system/example"
	cmd="make"
	bin_from="~/work/ukama/ukamaOS/distro/system/example/example.d"
	bin_to="/sbin/"

[build-rootfs]
	mkdir="/conf"

[build-conf]
        from="~/work/ukama/ukamaOS/distro/system/example/capp/conf/config.file"
        to="/conf/config.file"
	
# for [program:<exec>] in supervisor.conf
[capp-exec]
	name="example"
	version="latest"
	autostart="true"
	autorestart="false"
	bin="example.d"
	path="/sbin/" # path where the exec should be. Mathches build.bin_to
	args="-f /conf/config.file"
	envs="key1=value1"

# Nothing to see here. Move on

