# Config file for the microInit. 

# This files constitutes of two tables: 
#   1) Init config.
#   2) Init-bundles    
#

# Init Config: 
# Init config list all the bins required during init phase with image, version and path if required.
# 
# Init-bundle:
# These are singleshot containers started by init during bootup. These containers 
# are stopped once their task is  completed. Hence not required to be monitored.
# After init bundles are executed last step is to start microCE.
# 
# name = unique name of container which will be use to interact with it
# version := OCI image version. Default is "latest"
# 
# < Optional >
# image = image name which it is build from.
# path := OCI bundle path. This needs to be complete path. if not provided system would look at default path.
# 


# init 
[[init]]
    name = "init"
    version = "v0.0.1"

[[init]]
    name = "oci-runtime"
    image = "crun"
    version = "v0.0.1"
    path = "/usr/local/bin/crun"

[[init]]
    name = "microCE"
    image = "microCE"
    version = "v0.0.1" 
    path = "/usr/bin/microCE.d" 

# init-bundles
[[init_bundle]]
	name = "000-sysctl"
    image = "sysctl"
	path = "/containers/bundles/000-sysctl"
	version = "v0.0.1"

[[init_bundle]]
	name = "001-dhcpcd"
    image = "dhcpcd"
    version = "v0.0.1"
	path = "/containers/bundles/001-dhcpcd"

[[shutdown_bundle]]
	name = "000-shutdown"
    image = "shutdown"
    version = "v0.0.1"
	path = "/containers/bundles/000-000-shutdown"	

