name: pr-release-users
on:
  push:
    branches:
      - pr-release
  workflow_dispatch:

jobs:  
  build:
    runs-on: ubuntu-latest
    name: build users
    env: 
      working-directory: ./
    steps:
    - uses: actions/checkout@v3


    - name: build app
      uses: ./.github/actions/build-go
      with:
        registry-name: users
        working-directory: ${{ env.working-directory }}
        github-bot-token: ${{ secrets.UKAMA_BOT_GITHUB_TOKEN }}
        aws-secret-key: ${{ secrets.AWS_REGISTRY_SECRET_ACCESS_KEY }}
        aws-access-key: ${{ secrets.AWS_REGISTRY_ACCESS_KEY_ID }}

    - name: Init vars
      id: vars_step
      uses: ./.github/actions/git-vars

    - name: update gitops
      uses: denispalnitsky/gitops-release@v9
      with:
        filename: "releases/ukamax/pr-env.yaml"
        key: "usersImageTag"
        value:  ${{ steps.vars_step.outputs.sha_short }}
        github-token: ${{ secrets.UKAMA_BOT_GITHUB_TOKEN }}
        github-org-and-repo: "ukama/infra-as-code"
        github-user-mail: "bot@ukama.com"
        github-username: "ukama-bot"
